### PR TITLE
Add PR for help-wanted issues

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
@corylanou

**Comment by corylanou** [comment]
Should we add something in the blog about having them feel free to ask questions on the issues before they start if they need further clarification?

Otherwise this looks great.  +1!

**Comment by otoolep** [comment]
Doesn't it say that?

"We have tried to add some introductory notes to each issue to help you get started, and will make a particular effort to answer questions about these issues."

Does it need more emphasis?

**Comment by beckettsean** [comment]
I made some minor changes

:+1: @otoolep I say merge it.

**Comment by beckettsean** [comment]
@rkuchan or @gunnaraasen any opinions?

**Comment by gunnaraasen** [comment]
:+1:

**Pull request merged**
