### PR TITLE
Add note about the output of show servers from cli

### PR DESCRIPTION
**Pull request by mjdesa**
Feels contrived, but fixes https://github.com/influxdb/influxdb.com/issues/170

### CODE REVIEW

**Comment by beckettsean** [comment]
Do we need the preceding table or can we replace it with this new CLI output?

**Comment by mjdesa** [comment]
Could be just me, but I think that the table looks a lot better than the CLI output.

9sx1w3vlhjdkf85nmpbbuvvjcjei2p6wtwbibe241yi

**Comment by beckettsean** [comment]
Cool, works for me. :+1:

**Comment by mjdesa** [comment]
Just a clarification. Should I keep both, or just the table or just the cli output

**Comment by beckettsean** [comment]
You, @rkuchan, and @gunnaraasen should decide. I'm good with whatever the consensus is.

**Comment by rkuchan** [comment]
I like the CLI output - if the columns can line up.

**Pull request merged**
