### PR TITLE
WIP for downsampling docs

### PR DESCRIPTION
**Pull request by beckettsean**
fixes 159

### CODE REVIEW

**Comment by beckettsean** [comment]
fixes #160

**Comment by rkuchan** [comment]
I made several changes to `downsampling_and_retention.md`:
* Divided the initial discussion on RPs and CQs into sections (definition, purpose, and working with)
* Added a case study section to show an example of combining RPs and CQs
* Made edits

To do: 
* Update index
* Generally clean up the prose - not super happy with my additions right now
* Link to the extended discussion on CQ config options when that page is up
* Link to this page from the CQ page

I didn't include everything - I skim over creating RPs, creating CQs, and how to query/write to a non-`DEFAULT` RP. I also don't discuss the CQ config options and plan on linking to the extended discussion on them once that page goes live. Finally, I didn't talk about backreferencing (https://github.com/influxdb/influxdb/pull/3876) because I thought that should belong on the [CQ page](https://influxdb.com/docs/v0.9/query_language/continuous_queries.html).

**Comment by beckettsean** [comment]
@rkuchan is this still active or is there a replacement on docs.influxdata.com?

**Comment by rkuchan** [comment]
@beckettsean, still active - on my list to get it over to docs.influxdata.com.

**Comment by rkuchan** [comment]
Closed in favor of: https://github.com/influxdb/docs.influxdata.com/pull/94

**Pull request closed without merging**
