### PR TITLE
Don't indent everything!

### PR DESCRIPTION
**Pull request by toddboom**

### CODE REVIEW

**Comment by pauldix** [comment]
+1

**Comment by beckettsean** [comment]
This changes the layout for all pages, not just blog pages. I think the readability of the docs might be negatively affected. Any chance we can split the blog formatting from the docs formatting?

**Comment by toddboom** [comment]
@beckettsean better?

**Comment by gunnaraasen** [comment]
I think some padding beneath the `h3`'s would look better than taking out the indent.

**Comment by toddboom** [comment]
@gunnaraasen i think the indent is hard to read regardless, but i gave you a little extra `h3` margin.

**Comment by beckettsean** [comment]
+1

**Comment by gunnaraasen** [comment]
LGTM

**Comment by toddboom** [comment]
gracias, gentlemen!

**Pull request merged**
