### PR TITLE
mention no JOIN

### PR DESCRIPTION
**Pull request by beckettsean**

### CODE REVIEW

**Comment by beckettsean** [comment]
Simple PR but I want some review. Is this too simple? Is there somewhere else we should mention it? I'm trying to prevent the weekly "JOIN doesn't work" issue.

**Comment by otoolep** [comment]
Works for me. +1

**Comment by gunnaraasen** [comment]
Looks good. May also want to mention that tags replace the need for JOINs in most cases.

**Comment by beckettsean** [comment]
@gunnaraasen made some clarifying remarks, what do you think?

**Comment by gunnaraasen** [comment]
:+1:

**Comment by beckettsean** [comment]
no open issue for this

**Pull request merged**
