### PR TITLE
fixes issue#288

### PR DESCRIPTION
**Pull request by jackzampolin**
Fixes https://github.com/influxdb/influxdb.com/issues/288

### CODE REVIEW

**Comment by gunnaraasen** [comment]
This should go in the troubleshooting section. There's already an empty page for "System Monitoring".

**Comment by beckettsean** [comment]
I agree with @gunnaraasen, let's put this on https://github.com/influxdb/influxdb.com/blob/master/content/docs/v0.9/troubleshooting/system_monitoring.md

**Comment by jackzampolin** [comment]
Sorry for the whitespace deletion in schema_exploration.  Have fixed that problem so it won't happen again.

**Comment by beckettsean** [comment]
:+1:

**Pull request merged**
