### PR TITLE
Added MD5 checksums to download page

### PR DESCRIPTION
**Pull request by rossmcdonald**
I'm assuming the content here is okay. My main concern is on the formatting of the page, since the checksums appear a little dis-jointed from the downloads themselves. 

Let me know if I should modify anything.

### CODE REVIEW

**Comment by otoolep** [comment]
+1 on the importance of this.

But tow is this going to work? Do our packaging scripts now spit our checksums? If not, I fear this will son become a pain to maintain.

**Comment by rossmcdonald** [comment]
@beckettsean Checksum PR from our discussion yesterday. Does this look okay as far as the formatting goes?

**Comment by rossmcdonald** [comment]
@otoolep Ideally this will be automated at some point, but right now we'll just have to manually update this on every new release. Releases don't seem to be super frequent, so I'm hoping it's not too much of a pain.

Also nightly builds will not be provided checksums until its automated.

**Comment by otoolep** [comment]
How did you generate these checksums? Let's enhance `package.sh` to generate the checksums when the packages are generated, and dump the sums to stdout.

Sound good?

**Comment by otoolep** [comment]
At least that way, the sums are there, ready to go.

**Comment by rossmcdonald** [comment]
I just generated them all manually with `openssl dgst`, but I'll update the build script to spit them out on a packaging run.

**Comment by otoolep** [comment]
Great, thanks. That way they are there, and always generated the same way.

**Comment by gunnaraasen** [comment]
:+1:

**Comment by beckettsean** [comment]
:+1:

**Pull request merged**
