### PR TITLE
Adding an example for a downsampled CQ with subset of tags

### PR DESCRIPTION
**Pull request by khanduri**

### CODE REVIEW

**Comment by beckettsean** [comment]
thanks, @khanduri, looks good. We need you to sign the [CLA](https://influxdb.com/community/cla.html) before we can merge.

@rkuchan can you give another sign-off on this PR?

**Comment by rkuchan** [comment]
Looks good!

**Comment by khanduri** [comment]
@beckettsean  .. Done!

**Comment by beckettsean** [comment]
Thanks, @khanduri!

**Pull request merged**
