### PR TITLE
Proposal php sdk

### PR DESCRIPTION
**Pull request by gianarb**
Hi!
Now [corley/influxdb-php-sdk](https://github.com/corley/influxdb-php-sdk) supports v0.9.0..
Are you interested to add it into the list of clients?
Thanks

### CODE REVIEW

**Comment by beckettsean** [comment]
@gianarb thanks very much for the PR! We'll take a look.

**Comment by gianarb** [comment]
Thanks a lot! :+1:

**Comment by gianarb** [comment]
Hi @beckettsean! :) There are problems with this proposal? Can I help you to merge it?

Thanks!

**Comment by beckettsean** [comment]
@gianarb we're all heads-down at GopherCon this week but will take a look next week, thanks!

**Comment by beckettsean** [comment]
@gianarb Thanks for the port of the README from the PHO library. We've had internal discussions and have decided not to include full documentation for the libraries in our site docs, but instead provide links to the repos and their documentation.

https://github.com/corley/influxdb-php-sdk is already linked on https://influxdb.com/docs/v0.9/clients/api.html and has this content as the primary README, so we're going to close this PR.

**Comment by gianarb** [comment]
Thanks

**Pull request closed without merging**
