### PR TITLE
Copy edits for typos.

### PR DESCRIPTION
**Pull request by epc**
Believe I signed a CLA when this was influxdb.org.

### CODE REVIEW

**Comment by beckettsean** [comment]
Thanks for the edits, @epc! I don't see any record of the CLA being signed by your GitHub handle, nor anyone relevant named "Ed".

Can you perhaps [sign again](https://influxdb.com/community/cla.html)? We use the same CLA for all contributors, so it wouldn't be affected by the move from the influxdb.org to the influxdb.com repo.

**Comment by epc** [comment]
Odd, signing again (from my notes it looks like I signed the CLA and made my first contribution in November 2014).

**Comment by epc** [comment]
Note that I've signed the CLA.

**Comment by beckettsean** [comment]
Thanks, @epc, I do see you on the CLA sheet now. I can't explain why your previous signing wasn't recorded there, thanks for signing again.

**Pull request merged**
