### PR TITLE
restoring OS X installation instructions

### PR DESCRIPTION
**Pull request by beckettsean**
Someone created a tap so Homebrew works again.

### CODE REVIEW

**Comment by gunnaraasen** [comment]
:+1: nice! Works on my machine.

**Comment by gunnaraasen** [comment]
Also, version 0.8 installs the binary as `influxdb` so both versions 0.8 and 0.9 can be installed on the same machine.

**Comment by beckettsean** [comment]
@gunnaraasen that's cool, but I couldn't run the 0.8 recipe with 0.9 installed, I got errors:

```
$ brew tap
$ brew search influxdb
influxdb
homebrew/versions/influxdb08

$ brew install homebrew/versions/influxdb08
==> Tapping homebrew/versions
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-versions'...
remote: Counting objects: 235, done.
remote: Compressing objects: 100% (222/222), done.
remote: Total 235 (delta 24), reused 40 (delta 13), pack-reused 0
Receiving objects: 100% (235/235), 246.61 KiB | 152.00 KiB/s, done.
Resolving deltas: 100% (24/24), done.
Checking connectivity... done.
Tapped 232 formulae (256 files, 1.4M)
==> Installing influxdb08 from homebrew/homebrew-versions
Error: Cannot install homebrew/versions/influxdb08 because conflicting formulae are installed.

  influxdb: because Differing versions of the same formula

Please `brew unlink influxdb` before continuing.
```

Did you not get those, or did you have a workaround?

**Comment by gunnaraasen** [comment]
I mistakenly thought I had 0.9.2 installed via brew, but I had built it from source. I'm seeing the same error message.

**Pull request merged**
