### PR TITLE
Update doc with current temp fix for bug.

### PR DESCRIPTION
**Pull request by RobMcZag**
Problem highlighted in the doc on Mathematical Operators is now fixed with a temporary solution. Update the doc to reflect current status and quote from Philip O'Toole, author of the fix.

### CODE REVIEW

**Comment by beckettsean** [comment]
@mjdesa @otoolep please confirm this is correct?

@RobMcZag before we can merge we need you to sign the [CLA](https://influxdb.com/community/cla.html)

**Comment by otoolep** [comment]
This is fine, thanks @RobMcZag +1

**Comment by beckettsean** [comment]
@RobMcZag can you sign the CLA?

**Comment by RobMcZag** [comment]
I will check this morning with my Company. Should be fine, but I have to formally ask before signing.
I will update this when I have signed the CLA.

**Comment by RobMcZag** [comment]
@beckettsean  I have been approved by my company and I have signed the CLA.

**Comment by beckettsean** [comment]
Thanks, @RobMcZag. GDrive is down at the moment so I can't verify the CLA signing, but as soon as that's back up we'll get this merged.

**Comment by beckettsean** [comment]
GDrive is back and I confirm the CLA is signed. Thanks again @RobMcZag!

**Pull request merged**
