### PR TITLE
decrease padding on small devices

### PR DESCRIPTION
**Pull request by blairanderson**
#### What's this PR do?

- makes your site more readable on mobile devices

#### Where should the reviewer start?

https://github.com/influxdb/influxdb.com/commit/339bbbdffa8994a1670833d176d95547b7052225

#### Screenshots (if appropriate)

before:
screen shot 2015-09-30 at 9 50 57 am

after:
screen shot 2015-09-30 at 9 50 24 am

### CODE REVIEW

**Comment by beckettsean** [comment]
@benstronaut @alexpaxton can you check this CSS PR?

**Comment by jackzampolin** [comment]
Read the code changes and booted it up on local.  Looks great!  Think we should merge.

**Comment by blairanderson** [comment]
- first commit was editor removing unnecessary whitespace. 
- second was decreasing padding on mobile :+1:

**Comment by beckettsean** [comment]
@blairanderson we need you to sign the [CLA](https://influxdb.com/community/cla.html) before we can merge.

**Comment by blairanderson** [comment]
signed

**Comment by beckettsean** [comment]
Thanks for the PR, @blairanderson!

**Pull request merged**
